"""Translated 16-field header maps for Excel export.

Each language maps to the 16 canonical fields in this order:
bank_id, account_number, account_holder, statement_period_start,
statement_period_end, parser_version, language, transaction_date,
value_date, description, reference, debit, credit, amount,
balance, currency.
"""

from __future__ import annotations

from bank_parser.core.models import Language

# fmt: off
HEADER_MAP: dict[Language, list[str]] = {
    Language.ARABIC: [
        "معرف البنك",
        "رقم الحساب",
        "صاحب الحساب",
        "بداية الفترة",
        "نهاية الفترة",
        "إصدار المحلل",
        "اللغة",
        "تاريخ المعاملة",
        "تاريخ القيمة",
        "الوصف",
        "المرجع",
        "مدين",
        "دائن",
        "المبلغ",
        "الرصيد",
        "العملة",
    ],
    Language.URDU: [
        "بینک آئی ڈی",
        "اکاؤنٹ نمبر",
        "اکاؤنٹ ہولڈر",
        "مدت کا آغاز",
        "مدت کا اختتام",
        "پارسر ورژن",
        "زبان",
        "لین دین کی تاریخ",
        "ویلیو ڈیٹ",
        "تفصیل",
        "حوالہ",
        "ڈیبٹ",
        "کریڈٹ",
        "رقم",
        "بیلنس",
        "کرنسی",
    ],
    Language.RUSSIAN: [
        "ID банка",
        "Номер счёта",
        "Владелец счёта",
        "Начало периода",
        "Конец периода",
        "Версия парсера",
        "Язык",
        "Дата транзакции",
        "Дата валютирования",
        "Описание",
        "Референс",
        "Дебет",
        "Кредит",
        "Сумма",
        "Остаток",
        "Валюта",
    ],
    Language.SPANISH: [
        "ID del Banco",
        "Número de Cuenta",
        "Titular de Cuenta",
        "Inicio del Período",
        "Fin del Período",
        "Versión del Parser",
        "Idioma",
        "Fecha de Transacción",
        "Fecha de Valor",
        "Descripción",
        "Referencia",
        "Débito",
        "Crédito",
        "Monto",
        "Saldo",
        "Moneda",
    ],
    Language.HINDI: [
        "बैंक आईडी",
        "खाता संख्या",
        "खाताधारक",
        "अवधि प्रारंभ",
        "अवधि समाप्ति",
        "पार्सर संस्करण",
        "भाषा",
        "लेन-देन की तारीख",
        "मूल्य तिथि",
        "विवरण",
        "संदर्भ",
        "डेबिट",
        "क्रेडिट",
        "राशि",
        "शेष",
        "मुद्रा",
    ],
}
# fmt: on

# English fallback (for CLI and internal use)
HEADER_MAP_EN: list[str] = [
    "Bank ID",
    "Account Number",
    "Account Holder",
    "Period Start",
    "Period End",
    "Parser Version",
    "Language",
    "Transaction Date",
    "Value Date",
    "Description",
    "Reference",
    "Debit",
    "Credit",
    "Amount",
    "Balance",
    "Currency",
]
